---
# FILE:            alb-ha-cluster-infra.yml
# LICENSE:         Public Domain


# ansible-playbook -i hosts.yml alb-ha-cluster-infra.yml

- name: "alb-ha-cluster-infra: Playbook to manange the cluster underline infrastructure (not the apps)"
  # hosts: cluster_all_nodes
  hosts: none
  remote_user: root
  vars:
    # On this ap-alb-cluster-demo, we will use as example a single YAML file
    # containing all variables at /hosts.yml
    #
    # Note that ansible allows other types of inventories

  roles:
    - ap-application-load-balancer


# We will use https://github.com/DavidWittman/ansible-redis to setup an Redis cluster

- name: configure the master redis server
  hosts: redis_leader
  roles:
    - davidwittman.redis

- name: configure redis slaves
  hosts: redis_follower
  vars:
    # - redis_slaveof: redis-master.example.com 6379
  roles:
    - davidwittman.redis

- name: configure redis sentinel nodes
  hosts: redis_sentinel
  vars:
    #- redis_sentinel_monitors:
    #  - name: master01
    #    host: redis-master.example.com
    #    port: 6379
  roles:
    - davidwittman.redis