
---
# @see https://github.com/ansible/ansible/blob/devel/examples/hosts.yaml
# @see https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#splitting-out-host-and-group-specific-data

all:

  # As variaveis aqui são padrão para todos os grupos e hosts. Podem ser
  # sobrescritas individualmente mais tarde
  vars:
    alb_manange_all: yes
    alb_manange_sanitycheck: yes
    alb_manange_common: yes

    alb_manange_haproxy: yes
    alb_manange_openresty: yes
    alb_manange_ufw: yes

    alb_auth_users:
      - username: adminuser
        password: "plain-password-for-adminuser"
      - username: "otheradminuser"
        password: "another-password-here"

    alb_dmz:
      - ip: 173.249.10.99
        name: aguia-pescadora-delta.etica.ai
      - ip: 167.86.127.220
        name: aguia-pescadora-echo.etica.ai
      - ip: 167.86.127.225
        name: aguia-pescadora-foxtrot.etica.ai

    #alb_bastion_hosts:
    #  - ip: 192.0.2.255
    #    name: "You Can Put Here Your Own IP"

    alb_ufw_rules_always:
      - rule: limit
        port: 22
        proto: tcp
        comment: "Allows access from any IP on :22 on this ap-alb-cluster-demo instead of using alb_bastion_hosts"

    alb_haproxy_stats_enabled: yes
    alb_haproxy_stats_ip: 0.0.0.0 # 0.0.0.0 means exposed for everyone. Use firewall!
    alb_haproxy_stats_port: 8404
    alb_haproxy_stats_uri: "/haproxy?stats"
    alb_haproxy_stats_realm: "{{ alb_name }}: {{ inventory_hostname }}"

    # Note, just to avoid reach limits on Let'Encript, we will disable
    # for some time the letsencrypt default clause
    alb_letsencrypt_default: "return false"

  children:
    cluster_all_nodes:
      children:
        delta:
        echo:
        foxtrot:
    cluster_leader:
      children:
        delta:

    delta:
      hosts:
        aguia-pescadora-delta.etica.ai

    echo:
      hosts:
        aguia-pescadora-echo.etica.ai

    foxtrot:
      hosts:
        aguia-pescadora-foxtrot.etica.ai

