---
# FILE:            infra-alb.yml
# LICENSE:         Public Domain


# ansible-playbook -i hosts.yml infra-alb.yml
# ansible-playbook -i hosts.yml infra-alb.yml --tags="alb-haproxy"  # Apenas HAProxy
# ansible-playbook -i hosts.yml infra-alb.yml --tags="alb-ufw" --extra-vars "alb_forceredeploy=yes" # Apenas UFW

# To do some basic check for see if redis is listening, is possible to use
#    (printf "PING\r\n"; sleep 1) | nc aguia-pescadora-delta.etica.ai 6379
#    (printf "PING\r\n"; sleep 1) | nc aguia-pescadora-echo.etica.ai 6379
#    (printf "PING\r\n"; sleep 1) | nc aguia-pescadora-foxtrot.etica.ai 6379

- name: "alb-ha-cluster-infra: Playbook to manange the cluster underline infrastructure (not the apps)"
  hosts: cluster_all_nodes
  remote_user: root
  vars:
    # On this ap-alb-cluster-demo, we will use as example a single YAML file
    # containing all variables at /hosts.yml
    #
    # Note that ansible allows other types of inventories

  roles:
    - ap-application-load-balancer
