---
# FILE:            infra-alb.yml
# LICENSE:         Public Domain

# To run this playbook alone, use:
#     ansible-playbook -i hosts.yml infra-alb.yml
# To force ignore cached facts, use
#     ansible-playbook -i hosts.yml infra-alb.yml --extra-vars "alb_forceredeploy=yes"
# To run only one subcomponent and skipping facts, use the --tags=. For HAproxy:
#     ansible-playbook -i hosts.yml infra-alb.yml --tags="alb-haproxy" --extra-vars "alb_forceredeploy=yes"
# To just run the boostrap part
#     ansible-playbook infra-alb.yml --tags="alb-bootstrap" -i apd.etica.ai,

# To delete deployed apps and sysapps (for later rebuild from scrath)
#     ansible all -i hosts.yml -m shell -a "sudo rm -f /opt/alb/sysapps/*"
#     ansible all -i hosts.yml -m shell -a "sudo rm -f /opt/alb/apps/*"

# To delete cached facts
#     ansible all -i hosts.yml -m shell -a "sudo rm -f /etc/ansible/facts.d/*"

- name: "ansible-linux-ha-cluster: Playbook to manange the cluster underline infrastructure (not the apps)"
  hosts: cross_platform_test
  # hosts: ap_delta
  # hosts: ap_echo
  # hosts: ap_foxtrot
  remote_user: root
  gather_facts: true
  vars:
    # On this ap-alb-cluster-demo, we will use as example a single YAML file
    # containing all variables at /hosts.yml
    #
    # Note that ansible allows other types of inventories

  roles:
    - ap-application-load-balancer
