---
# FILE:            infra-consul.yml
# LICENSE:         Public Domain

# To run this playbook alone, use:
#     ansible-playbook -i hosts.yml infra-consul.yml

# About the Ansible Role provider
#   - https://github.com/brianshumate/ansible-consul
# About Consul
#   - https://www.consul.io
#   - https://www.consul.io/docs/index.html

- name: "ansible-linux-ha-cluster + brianshumate.consul: setup consul cluster"
  hosts: consul_instances
  roles:
    - brianshumate.consul
