---
# FILE:            infra-redis.yml
# LICENSE:         Public Domain


# ansible-playbook -i hosts.yml infra-redis.yml

# To do some basic check for see if redis is listening, is possible to use
#    (printf "PING\r\n"; sleep 1) | nc aguia-pescadora-delta.etica.ai 6379
#    (printf "PING\r\n"; sleep 1) | nc aguia-pescadora-echo.etica.ai 6379
#    (printf "PING\r\n"; sleep 1) | nc aguia-pescadora-foxtrot.etica.ai 6379

# We will use https://github.com/DavidWittman/ansible-redis to setup an Redis cluster

- name: "alb-ha-cluster-infra + davidwittman.redis: setup master, slave and sentinel"
  hosts: cluster_all_nodes
  roles:
    - davidwittman.redis
