---
# FILE:            infra-alb.yml
# LICENSE:         Public Domain

# To run this playbook alone, use:
#     ansible-playbook -i hosts.yml infra-alb.yml
# To force ignore cached facts, use
#     ansible-playbook -i hosts.yml infra-alb.yml --extra-vars "alb_forceredeploy=yes"
# To run only one subcomponent and skipping facts, use the --tags=. For HAproxy:
#     ansible-playbook -i hosts.yml infra-alb.yml --tags="alb-haproxy" --extra-vars "alb_forceredeploy=yes"

- name: "ansible-linux-ha-cluster: Playbook to manange the cluster underline infrastructure (not the apps)"
  hosts: cluster_all_nodes
  # hosts: delta
  remote_user: root
  vars:
    # On this ap-alb-cluster-demo, we will use as example a single YAML file
    # containing all variables at /hosts.yml
    #
    # Note that ansible allows other types of inventories

  roles:
    - ap-application-load-balancer
